USE HOSPITAL_DB;


--SELECT ALL PATIENT RECORDS;
 SELECT * FROM HEALTHCARE;

 --COUNT THE TOTOAL NUMBER OF PATIENTS 
 SELECT COUNT(*) AS TOTAL_PATIENT_COUNT FROM HEALTHCARE;

 --CHECK THE PATIENTNAME DUPLICATES
 SELECT NAME,
 COUNT(*)OVER (PARTITION BY NAME) DUPLICATE_COUNT
 FROM HEALTHCARE

-- CHECK THE PATIENTNAME DUPLICTAES WITH ALL COLUMNS TO CONFIRM 
SELECT * FROM HEALTHCARE WHERE NAME = 'AARON JONES'
SELECT * FROM HEALTHCARE WHERE NAME = 'AARON MILLER'
SELECT * FROM HEALTHCARE WHERE NAME = 'AARON PATEL'
SELECT * FROM HEALTHCARE WHERE NAME = 'ADAM CALLAHAN'
SELECT * FROM HEALTHCARE WHERE NAME = 'ALEXANDER HARRIS'
SELECT * FROM HEALTHCARE WHERE NAME = 'ALEXANDER TURNER'
SELECT * FROM HEALTHCARE WHERE NAME = 'ZACHARY HICKS'
SELECT * FROM HEALTHCARE WHERE NAME = 'WILLIAM SMITH'
SELECT * FROM HEALTHCARE WHERE NAME = 'WILLIAM THOMPSON'
SELECT * FROM HEALTHCARE WHERE NAME = 'WILLIAM HARRIS'
SELECT * FROM HEALTHCARE WHERE NAME = 'WILLIAM JOHNSON'

-- COUNT THE NUMBER OF MALE PATIENTS;
SELECT COUNT(GENDER) AS TOTOL_MALEPATIENTS_COUNT
FROM HEALTHCARE
WHERE GENDER = 'MALE' ;

-- COUNT THE NUMBER OF FEMALE PATIENTS;
SELECT COUNT(GENDER) AS TOTOL_FEMALEPATIENTS_COUNT
FROM HEALTHCARE 
WHERE  GENDER = 'FEMALE'

--SHOW UNIQUE BLOOD TYPES IN HOSPITAL
 SELECT DISTINCT(BLOOD_TYPE) FROM HEALTHCARE;

 --SHOW UNIQUE INSURANCEPROVIDERS TYPES IN HOSPITAL
 SELECT DISTINCT(INSURANCE_PROVIDER) FROM HEALTHCARE;

--SHOW UNIQUE MEDICAL_CONDTION TYPES IN HOSPITAL
 SELECT DISTINCT(MEDICAL_CONDITION) FROM HEALTHCARE;

--CALCULATE TOTAL BILLING AMOUNT FOR ALL PATIENTS
SELECT ROUND(SUM(BILLING_AMOUNT),2) AS TOTAL_BILL FROM HEALTHCARE;

--GET THE AVERAGE AGE OF ADMITTED PATIENTS
SELECT AVG(AGE) AS AVERAGE_AGE FROM HEALTHCARE;

--FIND THE MOST COMMON ADMISSION TYPE
SELECT TOP 1 ADMISSION_TYPE, COUNT(*) AS COUNT
FROM HEALTHCARE
GROUP BY ADMISSION_TYPE
ORDER BY COUNT DESC


--RETRIEVE PATIENTS SORTED BY THEIR BILLING AMOUNT (HIGHEST FIRST)
SELECT * FROM HEALTHCARE ORDER BY (BILLING_AMOUNT) DESC;

--FIND THE TOP 3 DOCTORS WHO ADMITTED THE MOST PATIENTS
SELECT TOP 3 DOCTOR, COUNT(*) AS PATIENT_COUNT
FROM HEALTHCARE
GROUP BY DOCTOR
ORDER BY PATIENT_COUNT DESC


--CALCULATE THE TOTAL BILLING AMOUNT PER INSURANCE PROVIDER
SELECT INSURANCE_PROVIDER, ROUND(SUM(BILLING_AMOUNT),2) AS TOTAL_BILLING
FROM HEALTHCARE
GROUP BY INSURANCE_PROVIDER
ORDER BY TOTAL_BILLING DESC;

--FIND PATIENTS WHO STAYED FOR MORE THAN 10 DAYS (USING DATEDIFF)
SELECT NAME, 
       DATEDIFF(DAY, DATE_OF_ADMISSION, DISCHARGE_DATE) AS STAY_DURATION
FROM HEALTHCARE
WHERE DATEDIFF(DAY, DATE_OF_ADMISSION, DISCHARGE_DATE) > 10;

--FIND DUPLICATE PATIENTS WITH THE SAME NAME AND AGE
SELECT NAME, AGE, COUNT(*)
FROM HEALTHCARE
GROUP BY NAME, AGE
HAVING COUNT(*) > 1;

--RETRIEVE THE MOST EXPENSIVE PATIENT BILLING CASE
SELECT TOP 1  * FROM HEALTHCARE
ORDER BY BILLING_AMOUNT DESC


--FIND PATIENTS WHO HAVEN'T BEEN DISCHARGED YET (NULL VALUES)
SELECT * FROM HEALTHCARE WHERE DISCHARGE_DATE IS NULL;

--RANK PATIENTS BY BILLING AMOUNT USING RANK()
SELECT NAME, BILLING_AMOUNT, 
       RANK() OVER (ORDER BY BILLING_AMOUNT DESC) AS RANK
FROM HEALTHCARE;

--GET THE TOTAL NUMBER OF ADMISSIONS PER MONTH
SELECT MONTH(DATE_OF_ADMISSION) AS MONTH, COUNT(*) AS ADMISSIONS
FROM HEALTHCARE
GROUP BY MONTH(DATE_OF_ADMISSION)
ORDER BY MONTH;

--USE CASE STATEMENT TO CATEGORIZE PATIENTS BASED ON AGE
SELECT NAME, AGE,
       CASE 
           WHEN AGE < 18 THEN 'CHILD'
           WHEN AGE BETWEEN 18 AND 60 THEN 'ADULT'
           ELSE 'SENIOR'
       END AS AGE_CATEGORY
FROM HEALTHCARE;

--FIND THE PERCENTAGE CONTRIBUTION OF EACH DOCTOR’S PATIENTS TO TOTAL ADMISSIONS
SELECT DOCTOR, COUNT(*) AS PATIENT_COUNT, 
       (COUNT(*) * 100.0) / (SELECT COUNT(*) FROM HEALTHCARE) AS PERCENTAGE
FROM HEALTHCARE
GROUP BY DOCTOR
ORDER BY PERCENTAGE DESC;

-- FIND PATIENTS ADMITTED IN A SPECIFIC YEAR (E.G., 2023)
SELECT * FROM HEALTHCARE WHERE YEAR(DATE_OF_ADMISSION) = 2023;

--FIND THE DOCTOR WITH THE HIGHEST AVERAGE BILLING PER PATIENT
SELECT TOP 1 DOCTOR, ROUND(AVG(BILLING_AMOUNT),0) AS AVG_BILLING
FROM HEALTHCARE
GROUP BY DOCTOR
ORDER BY AVG_BILLING DESC;


--IDENTIFY PATIENTS WITH MULTIPLE HOSPITAL ADMISSIONS
SELECT NAME, COUNT(*) AS ADMISSION_COUNT
FROM HEALTHCARE
GROUP BY NAME
HAVING COUNT(*) > 1;

--FIND PATIENTS WHOSE BILLING AMOUNT IS ABOVE THE AVERAGE

SELECT * FROM HEALTHCARE
WHERE BILLING_AMOUNT > (SELECT AVG(BILLING_AMOUNT) FROM HEALTHCARE);


--ROLLING TOTAL OF ADMISSIONS PER MONTH (CUMULATIVE COUNT OVER TIME)
SELECT MONTH(DATE_OF_ADMISSION) AS MONTH, 
       YEAR(DATE_OF_ADMISSION) AS YEAR, 
       COUNT(*) AS MONTHLY_ADMISSIONS, 
       SUM(COUNT(*)) OVER (ORDER BY YEAR(DATE_OF_ADMISSION), MONTH(DATE_OF_ADMISSION)) AS CUMULATIVE_ADMISSIONS
FROM HEALTHCARE
GROUP BY YEAR(DATE_OF_ADMISSION), MONTH(DATE_OF_ADMISSION)
ORDER BY YEAR, MONTH ;

--FIND THE MOST COMMON MEDICAL CONDITION BY GENDER
SELECT GENDER, MEDICAL_CONDITION, COUNT(*) AS CONDITION_COUNT
FROM HEALTHCARE
GROUP BY GENDER, MEDICAL_CONDITION
ORDER BY CONDITION_COUNT DESC;

--FIND PATIENTS WHOSE AGE IS ABOVE THE AVERAGE FOR THEIR ADMISSION TYPE

SELECT NAME, AGE, ADMISSION_TYPE
FROM HEALTHCARE H1
WHERE AGE > (SELECT AVG(AGE) FROM HEALTHCARE H2 WHERE H1.ADMISSION_TYPE = H2.ADMISSION_TYPE);
































 
 
 
 



 

