

SELECT * FROM HEALTHCARE;

--CREATE STORED PROCEDURE TO GET THE RECORDS
CREATE PROCEDURE ALL_RECORDS
AS
BEGIN
SELECT * 
FROM	HEALTHCARE;
END;

-- PROCEDURE EXECUTION
EXEC ALL_RECORDS;

--CREATE STORED PRODECURE FOR PATIENTS MEDICAL_CONDTION

CREATE PROCEDURE ALL_PATIENTS @MEDICAL_CONDITION NVARCHAR(50)
AS
BEGIN
SELECT NAME, 
AGE, 
GENDER , 
BLOOD_TYPE 
FROM HEALTHCARE   WHERE MEDICAL_CONDITION = @MEDICAL_CONDITION;
 END;

 --PROCEDURE EXECUTION
EXEC ALL_PATIENTS @MEDICAL_CONDITION = 'CANCER'

--CREATE STORED PROCEDURE FOR BILLING AMOUNT PAID BY INSURANCE PROVIDERS BASED ON MEDICAL CONDITION
CREATE PROCEDURE  TOTAL_BILLING_AMOUNT @INSURANCE_PROVIDER NVARCHAR , @MEDICAL_CONDITION NVARCHAR
AS
BEGIN
SELECT NAME, 
 AGE ,
GENDER, 
 HOSPITAL,
 ADMISSION_TYPE ,
 DATE_OF_ADMISSION, 
 DISCHARGE_DATE 
 FROM HEALTHCARE 
 WHERE INSURANCE_PROVIDER = @INSURANCE_PROVIDER AND MEDICAL_CONDITION = @MEDICAL_CONDITION
 END;

 --PROCEDURE EXECUTION
EXEC TOTAL_BILLING_AMOUNT @INSURANCE_PROVIDER = 'MEDICARE', @MEDICAL_CONDITION ='OBESITY';