

--CREATE VIEW WITH ADM_TYPE_ELECTIVE
CREATE VIEW ADM_TYPE_ELECTIVE
AS
SELECT 
NAME,
AGE,
GENDER, 
HOSPITAL,
MEDICAL_CONDITION,
DATE_OF_ADMISSION,
DISCHARGE_DATE,
DATEDIFF(DAY,DATE_OF_ADMISSION,DISCHARGE_DATE)AS STAY_DURATION
FROM HEALTHCARE 
WHERE ADMISSION_TYPE = 'ELECTIVE'


-- GET THE RECORDS FROM THE  VIEW
SELECT * FROM ADM_TYPE_ELECTIVE

--CREATE VIEW WITH ADM_TYPE_EMERGENCY
CREATE VIEW ADM_TYPE_EMERGENCY
AS
SELECT 
NAME,
AGE,
GENDER, 
HOSPITAL,
MEDICAL_CONDITION,
DATE_OF_ADMISSION,
DISCHARGE_DATE,
DATEDIFF(DAY,DATE_OF_ADMISSION,DISCHARGE_DATE)AS STAY_DURATION
FROM HEALTHCARE 
WHERE ADMISSION_TYPE = 'EMERGENCY'

-- GET THE RECORDS FROM THE  VIEW
SELECT * FROM ADM_TYPE_EMERGENCY

--CREATE VIEW WITH ADM_TYPE_URGENT
CREATE VIEW ADM_TYPE_URGENT
AS
SELECT 
NAME,
AGE,
GENDER, 
HOSPITAL,
MEDICAL_CONDITION,
DATE_OF_ADMISSION,
DISCHARGE_DATE,
DATEDIFF(DAY,DATE_OF_ADMISSION,DISCHARGE_DATE)AS STAY_DURATION
FROM HEALTHCARE 
WHERE ADMISSION_TYPE = 'URGENT'

-- GET THE RECORDS FROM THE  VIEW
SELECT * FROM ADM_TYPE_URGENT


-- GET THE UNITEDHEALTH  BIILING AMOUNT
CREATE VIEW  UH_IP_BILLING
AS
SELECT
NAME,
AGE,
GENDER,
ROUND(SUM(BILLING_AMOUNT),0) AS TOTAL_BILLAMOUNT
FROM HEALTHCARE
WHERE INSURANCE_PROVIDER = 'UNITEDHEALTHCARE'
GROUP BY NAME,AGE,GENDER;

--GET THE RECORDS FROM THE  VIEW
SELECT * FROM UH_IP_BILLING

-- GET THE MEDICARE BIILING AMOUNT
CREATE VIEW  MC_IP_BILLING
AS
SELECT
NAME,
AGE,
GENDER,
ROUND(SUM(BILLING_AMOUNT),0) AS TOTAL_BILLAMOUNT
FROM HEALTHCARE
WHERE INSURANCE_PROVIDER = 'MEDICARE'
GROUP BY NAME,AGE,GENDER;

--GET THE RECORDS FROM THE  VIEW
SELECT * FROM MC_IP_BILLING

-- GET THE AETNA BIILING AMOUNT
CREATE VIEW  AT_IP_BILLING
AS
SELECT
NAME,
AGE,
GENDER,
ROUND(SUM(BILLING_AMOUNT),0) AS TOTAL_BILLAMOUNT
FROM HEALTHCARE
WHERE INSURANCE_PROVIDER = 'AETNA'
GROUP BY NAME,AGE,GENDER;

--GET THE RECORDS FROM THE  VIEW
SELECT * FROM AT_IP_BILLING

-- GET THE BLUE CROSS BIILING AMOUNT
CREATE VIEW  BC_IP_BILLING
AS
SELECT
NAME,
AGE,
GENDER,
ROUND(SUM(BILLING_AMOUNT),0) AS TOTAL_BILLAMOUNT
FROM HEALTHCARE
WHERE INSURANCE_PROVIDER = 'BLUE CROSS'
GROUP BY NAME,AGE,GENDER;

--GET THE RECORDS FROM THE  VIEW
SELECT * FROM BC_IP_BILLING

-- GET THE CIGNA BIILING AMOUNT
CREATE VIEW  CG_IP_BILLING
AS
SELECT
NAME,
AGE,
GENDER,
ROUND(SUM(BILLING_AMOUNT),0) AS TOTAL_BILLAMOUNT
FROM HEALTHCARE
WHERE INSURANCE_PROVIDER = 'CIGNA'
GROUP BY NAME,AGE,GENDER;

--GET THE RECORDS FROM THE  VIEW
SELECT * FROM CG_IP_BILLING

